# version key - used to issue warnings about breaking changes.
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:13.0.0
    steps:
      - checkout

      # ... steps for building/testing app ...
      - run: echo "no tests"

      - run: |
          docker --version
          docker build -t simple-node .
          docker tag simple-node mosessofteng/simple-node:latest

      - run:
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push mosessofteng/simple-node
